version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: accountantbot_db
    env_file: [.env]
    environment:
      POSTGRES_DB: accountant_bot
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # Redis cache / key-value store
  redis:
    image: redis:7-alpine
    container_name: accountantbot_redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
