package com.example.demo.model.enums;

public enum DialogStateType {
    NONE,
    IDLE,
    AWAITING_AMOUNT,
    AWAITING_CURRENCY,
    AWAITING_CATEGORY_FOR_EXPENSE,
    AWAITING_SOURCE_FOR_INCOME,
    AWAITING_SUBCATEGORY,
    AWAITING_DESCRIPTION,
    AWAITING_ACCOUNT_AND_DATE,
    AWAITING_CONFIRMATION,
    EDIT_FIELD_SELECTION,
    AWAITING_EDIT_VALUE,
    CANCELLED,
    ERROR_RECOVERY,
    HELP_CONTEXT,
    SUCCESS
}
